name: Deploy with Environments

# Trigger events - specifies when this workflow should run
on:
  push:  # The workflow runs whenever a push is made to the specified branch
    branches:
      - main  # Fixed typo here

jobs:  # Defines the series of tasks the workflow will execute
  deploy:  # Name of this job
    runs-on: ubuntu-latest
    
    steps:  # Steps to execute within the job
      - name: Checkout Code
        uses: actions/checkout@v3  # GitHub action to clone the repo into the runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Application
        env:
          # Sensitive information: GitHub Secrets
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEW_API_KEY: ${{ secrets.NEW_API_URL }}
          OPENAI_API_DEPLOYMENT: ${{ secrets.OPENAI_API_DEPLOYMENT }}
          
          # Non-sensitive information: GitHub Environment variables
          OPEN_API_DEPLOYMENT: ${{ vars.OPENAI_API_DEPLOYMENT }}
          OPENAI_API_MODEL: ${{ vars.OPENAI_API_MODEL }}
          AZURE_OPENAI_ENDPOINT: ${{ vars.AZURE_OPENAI_ENDPOINT }}
          OPENAI_API_VERSION: ${{ vars.OPENAI_API_VERSION }}
        run: |
          nohup python -m uvicorn server:app --host 0.0.0.0 --port 8000 &
          sleep 5  # Allow server some time to start
